spring:
  application:
    name: boardtest

  datasource:
    url: jdbc:mysql://localhost:3306/exampledb
    username: oniwon
    password: 89800
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 80